version: '3.8'

services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    expose:
        - 2181

  kafka:
    image: wurstmeister/kafka:latest
    depends_on:
    - zookeeper
    container_name: kafka
    expose:
    - 9092
    ports:
    - 9092:9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_PORT: 9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_BROKER_ID: 0
      KAFKA_ADVERTISED_LISTENERS:  PLAINTEXT://:9092
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
     # KAFKA_ADVERTISED_HOST_NAME: kafka


networks:
   default:
       name: kaf-net