version: '3.3'

services:


  zookeeper:

    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    expose:
        - 2181


  kafka:

    image: wurstmeister/kafka:latest
    depends_on:
    - zookeeper
    container_name: kafka
    expose:
    - 9092
    ports:
    - 9092:9092
    environment:

      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_PORT: 9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_BROKER_ID: 0
     # KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://35.239.124.210:9092, PLAINTEXT://kafka:9092
     # KAFKA_LISTENERS: PLAINTEXT://:9092, PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ADVERTISED_HOST_NAME: 104.197.84.201


networks:
   default:
     external:
       name: kaf-net        