version: '3.3'

services:

  zookeeper:
    image: wurstmeister/zookeeper:latest
    restart: always
    env_file:
    - conf.env
    
    container_name: zookeeper
    expose:
        - 2181


  kafka:
    image: wurstmeister/kafka:latest
    restart: always
    depends_on:
    - zookeeper
    container_name: kafka
    expose:
    - 9092
    ports:
    - 9092:9092
    env_file:
    - conf.env
    
  
  mongodb:
    restart: always
    container_name: mongodb
    image: mongo:latest
    env_file:
    - conf.env

    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db


volumes:
  mongodb_data_container:

networks:
   default:
     external:
       name: kaf-net        
