version: '3.8'

x-environment: &commonEnv
  MONGO_INITDB_ROOT_USERNAME: admin
  MONGO_INITDB_ROOT_PASSWORD: password
  
services:
  displaycontents:
    container_name: displaycontents
    build: ./display
    environment: *commonEnv
    depends_on: mongodb

  mongodb:
    restart: always
    container_name: mongodb
    image: mongo:latest
    environment: *commonEnv
      
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db


volumes:
  mongodb_data_container:

networks:
   default:
       name: mongo-net
